library(Seurat)
library(ggplot2)
library(magrittr)
library(dplyr)
library(ggrepel)
library(stringr)
library(tidyverse)
source("/Users/jalon/Desktop/newest scripts/functions/colors.R")
source("/Users/jalon/Desktop/newest scripts/functions/percent_plot.R")
source("/Users/jalon/Desktop/newest scripts/functions/myvolcano.R")
source("/Users/jalon/Desktop/newest scripts/functions/myfeatureplot.R")
source("/Users/jalon/Desktop/newest scripts/functions/myfindmarkers.R")
source("/Users/jalon/Desktop/newest scripts/functions/myGSVA.R")
source("/Users/jalon/Desktop/newest scripts/functions/mymodule_score.R")
source("/Users/jalon/Desktop/newest scripts/functions/stacked_violin_plot.R")

